version: '3'
services:
  eureka-server:
    build: ./EurekaServer
    image: spring-cloud/eureka
    container_name: eureka-server
    ports:
      - "8761:8761"

  node1:
    build: ./Worker
    container_name: node1
    environment:
      - eureka.client.serviceUrl.defaultZone=http://eureka-server:8761/eureka
      - spring.application.name=Node1
    volumes:
      - ./Storage/Node1:/app/Storage/Node1
      - ./Storage/Node1/Users:/app/Storage/Node1/Users
    ports:
      - "8081:8080"
    depends_on:
      - eureka-server
    links:
      - eureka-server
  node2:
    build: ./Node
    container_name: node2
    environment:
      - eureka.client.serviceUrl.defaultZone=http://eureka-server:8761/eureka
      - spring.application.name=Node2
    volumes:
      - ./Storage/Node2:/app/Storage/Node2
      - ./Storage/Node2/Users:/app/Storage/Node2/Users
    ports:
      - "8082:8080"
    depends_on:
      - eureka-server
    links:
      - eureka-server

