version: '3'
services:
  eureka-server:
    build: ./eureka-server
    image: spring-cloud/eureka
    container_name: eureka-server
    ports:
      - "9090:9090"
  node1:
    build: ./Worker
    container_name: node1
    environment:
      - eureka.client.serviceUrl.defaultZone=http://eureka-server:9090/eureka
      - spring.application.name=Node
      - node.name=Node1
      - server.port=8081
    volumes:
      - ./Storage/Node1-Storage:/Storage/Node1-Storage
      - ./Storage/Node1-Storage/users.json:/Storage/Node1-Storage/users.json
    ports:
      - "8081:8081"
    depends_on:
      - eureka-server
      - broker
    links:
      - eureka-server
  node2:
    build: ./Worker
    container_name: node2
    environment:
      - eureka.client.serviceUrl.defaultZone=http://eureka-server:9090/eureka
      - spring.application.name=Node
      - node.name=Node2
      - server.port=8082
    volumes:
      - ./Storage/Node2-Storage:/Storage/Node2-Storage
      - ./Storage/Node2-Storage/users.json:/Storage/Node2-Storage/users.json
    ports:
      - "8082:8082"
    depends_on:
      - eureka-server
      - broker
    links:
      - eureka-server
  node3:
    build: ./Worker
    container_name: node3
    environment:
      - eureka.client.serviceUrl.defaultZone=http://eureka-server:9090/eureka
      - spring.application.name=Node
      - node.name=Node3
      - server.port=8083
    volumes:
      - ./Storage/Node3-Storage:/Storage/Node3-Storage
      - ./Storage/Node3-Storage/users.json:/Storage/Node3-Storage/users.json
    ports:
      - "8083:8083"
    depends_on:
      - eureka-server
      - broker
    links:
      - eureka-server

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181

  broker:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_HOST://broker:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1